### ISSUE TITLE
Add Discord Support Link

### ISSUE THREAD

**Issue by ghost** [XenKys/disgroove#3]
Would be nice to add a Discord Invite Server Link for the support and receive new announcements from there

**Comment by sergiogotuzzo** [comment]
Coming soon

**Comment by XenKys** [comment]
Coming soon

**Comment by sergiogotuzzo** [comment]
https://discord.gg/kunfRQgRyD
Soon will be added to the README

**Comment by sergiogotuzzo** [comment]
Added to the README

**Comment by sergiogotuzzo** [comment]
Discord Server deleted

**Comment by voltflake** [comment]
@sergiogotuzzo There are no other support channels other than non-existing discord server?

**Comment by sergiogotuzzo** [comment]
> @sergiogotuzzo There are no other support channels other than non-existing discord server?

You can ask help by opening an issue.
The Discord server was deleted because in it there was only me.
